### ISSUE TITLE
Reference implementation options and checks which aren't in the spec

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#14]
The reference implementation of [jsonld-signatures](https://github.com/digitalbazaar/jsonld-signatures) includes some options and some checks that aren't mentioned in the spec.  Specifically:

On verify:
- `publicKey`
- `publicKeyOwner`
- `checkKey`
- `checkKeyOwner` (some or all of which these last four may be combined into a [publicKey procedure instead](https://github.com/digitalbazaar/jsonld-signatures/pull/23#issuecomment-308193545)?)
- `checkNonce`
- `checkDomain`
- `checkTimestamp`
- `maxTimestampDelta`
- `documentLoader`
- `id`

Maybe these aren't things that need to be specified in the algorithm, because they're more of library-specific options?  Still a bunch of these correspond to good things to check, such as checking the timestamp and the nonce and etc, of which we have no recommendations to do anything about these in the algorithm steps in the spec as-is.

**Comment by msporny** [comment]
> Maybe these aren't things that need to be specified in the algorithm, because they're more of library-specific options? 

Yes, some of them are library specific, some of them are experimental, etc. We are trying not to be too prescriptive to implementers.

> Still a bunch of these correspond to good things to check, such as checking the timestamp and the nonce and etc, of which we have no recommendations to do anything about these in the algorithm steps in the spec as-is.

The [Signature Algorithm](https://w3c-dvcg.github.io/ld-signatures/#signature-algorithm), step 5 includes timestamp, nonce, domain, and any other data in the `signature options` - it's arbitrarily extensible... the entire graph under `signature` MUST be included if specified. We probably need to do a better job in the spec pointing this out. So, for example... if you include something like `object.signature.foo` ... then `object.signature.foo` will be included in the signature graph that's canonicalized and hashed. If you don't do that, you're not in conformance with the spec. The same goes for verification, you need to make sure **everything** in the signature field is included when generating the verification hash.

So, there is a MUST requirement, but it seems like that's not clear from the spec text. Thoughts, @cwebber?

**Comment by cwebber** [comment]
I think it wasn't clear to me to what extent we were being prescriptive about what `options` should be as actual arguments in terms of being prescriptive about an API (I remember when working on implementing a json-ld library that I read [this section](https://json-ld.org/spec/latest/json-ld-api/#the-application-programming-interface) as suggesting that a very specific procedure API be provided, but I see now that even that was fairly non-normative).  Anyway, I understand that mistake in conflating those meanings of `options` now and that we want the spectext to be fairly hands-off.

The one thing that seems worth mentioning checking that isn't in any way mentioned in the spec (as in terms of a good practice) is maybe the timestamp delta check, but that doesn't seem to be core to this.  I'm okay with closing this since I think resolving language in #13 will resolve confusion here.
