### ISSUE TITLE
Is framing required?

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#19]
It seems to me that in attaching a signature (and probably in verifying, though I guess you can search for all signatures) you need to know the root or id of where the signature will be attached / verified from.  This isn't said in the spec though.

Note that a similar issue comes up in ocap-ld because you need to know which subject is the invocation that you're verifying.  Which makes sense... as we generalize this to ld-proofs and make ocap-ld be a "plugin" to that system, it's totally reasonable and sensible that the same issue exists there.

**Comment by cwebber** [comment]
Sorry, I should clarify: by "is framing required" I'm using a shorthand for "either it's already in a tree or if in graph soup form you know what the root subject's id is that you're verifying"

**Comment by cwebber** [comment]
To clarify, say we have:

``` python
myjld = {
  "@id": "https://foo/",
  "https://example/#bar": {
    "@id": "https://bar",
    "https://example/#foo": {
      "@type": "@id",
      "@id": "https://foo/"}}}

jsonld.sign(myjld, privkey) # or whatever argument order
```

Where does the `signature` / `proof` get attached when signing?  Current implementations attach it to the toplevel subject.  But that's cheating from a graph perspective; how do we know what the toplevel subject is?  After all, in n-quads, the above document is:

```
<https://bar> <https://example/#foo> <https://foo/> .
<https://foo/> <https://example/#bar> <https://bar> .
```

To put it another way, how would you do the following:

``` python
jsonld.sign(quads, privkey)
```

You would have to, one way or another, specify which subject is the subject being signed.  Lord help you if the subject that should get the signature is a blank node.

**Comment by cwebber** [comment]
Dave and I talked about it, and we agreed that framing is not required, but knowing what the "root" subject being dealt with (to attach a proof, or to verify it, if not verifying all recursively) does need to be specified if coming from graph soup form, but that it's automatically implied if coming from json-ld form.

**Comment by dmitrizagidulin** [comment]
Sounds like the issue has been addressed, closing. (Feel free to reopen on the https://github.com/w3c-ccg/ld-proofs/ repo if not.)
