### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sandhawke** [w3c-ccg/ld-signatures#2]
I'm trying to find the canonicalization algorithm and all the links from the spec seem to be broken.

https://w3id.org/security#GCA2015 occurs in free text as an example, but there's no such fragment in that document.   The text "GCA" never even occurs.

Elsewhere we see  "(e.g. the GCA2015 [RDF-DATASET-CANONICALIZATION] algorithm). " which links to 

[RDF-DATASET-CANONICALIZATION]
    RDF Dataset CANONICALIZATION. David Longley; Manu Sporny. JSON-LD Community Group. CGDRAFT. URL: http://json-ld.github.io/CANONICALIZATION/spec/ 

But that's 404.

**Comment by gkellogg** [comment]
That should probably be http://json-ld.github.io/normalization/spec/

**Comment by dmitrizagidulin** [comment]
Link has been fixed in PR #3, this can be closed.
