### ISSUE TITLE
The "owner" field... is it necessary?

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#20]
At Rebooting Web of Trust fall 2017 I was surprised and intrigued to see just how much confusion the "owner" field caused.  To me it seemed like a no-brainer, especially since I was interested in using LDS to verify that X entity really did make Y statement on the ActivityPub network... if Manu was making a statement that he liked ravioli, I absolutely should be able to check that this was signed by a key that really was by Manu.  A few months later at TPAC I came to understand why Mark was so confused: most of the LDS use cases were focused around "who said what", but what Mark was really interested in was, "does the agent have the authority to perform this action".  If instead I am entrusting Manu with the ability to launch a nuclear missile, I may instead issue a capability to one of Manu's specific keys, and it may be a one-off key, and in fact we don't need to have *any* concept of identity attached to this necessarily.  (This jokingly lead to the conclusion that nuclear missiles are an easy problem while talking about ravioli is a hard one.)

Some time later and the divisions between verifiable credentials and ocap-ld have made some more things clear: VCs are about identity and reasoning about identity, and ocap-ld is about authority and possession.  So it makes sense that Mark was confused, since we don't in that case need to tie the key back to any concept of "owner".  But we do need something *like* owner in the case of something like verifiable credentials or messages we read on the activitypub network, where we care a lot about being sure that some identity really was the one who made some statement.

So it seems that we do need something like "owner" in the case that an identity is making some sort of assertions.  Except... except!  I think that it turns out that in the systems I've seen so far, "owner" has turned out to be redundant anyway!  Consider... ActivityStreams has the `actor` and `attributedTo` fields:

``` javascript
  {"@context": "https://www.w3.org/ns/activitystreams",
   "type": "Create",
   "id": "https://social.example/alyssa/posts/a29a6843-9feb-4c74-a7f7-081b9c9201d3",
   "to": ["https://chatty.example/ben/"],
   "actor": "https://social.example/alyssa/",
   "object": {"type": "Note",
              "id": "https://social.example/alyssa/posts/49e2d03d-b53a-4c4c-a95c-94a6abf45a19",
              "attributedTo": "https://social.example/alyssa/",
              "to": ["https://chatty.example/ben/"],
              "content": "Say, did you finish reading that book I lent you?"}}
```

And even Verifiable Credentials has the `issuer` field:

``` javascript
{
  "id": "http://dmv.example.gov/credentials/3732",
  "type": ["VerifiableCredential", "ProofOfAgeCredential"],
  "issuer": "https://dmv.example.gov/issuers/14",
  "issued": "2010-01-01T19:73:24Z",
  "claim": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "ageOver": 21
  },
  "proof": { ... }
}
```

So it seems to me that we don't need "owner" at all.  In either of these cases, we can see if the key that's in the proof lines up with either the `actor`/`attributedTo` or `issuer` respectively.  No need for owner.

**Comment by dlongley** [comment]
That there are cases when `owner` may be redundant does not mean that `owner` is never needed or that it isn't useful to have a common verification process across all the use cases -- whereby the only additional check that must be made in the use cases you've presented here is a comparison of the `owner` against the `issuer` or `actor`. This can be done in a layered way that is non-intrusive to the standard verification implementation.

I imagine the removal of owner will make the implementation/verification process more complex in return for negligible benefit.

**Comment by cwebber** [comment]
I think this is incorrect for several reasons, which I will aim to articulate further later, but:

- Which field do we look for the key in in the owner anyway?  Currently it's `privateKey` but in the glorious generalized future of linked data proofs it may be different depending on the `proofPurpose`, right?  Because we won't just be having a single `proofPurpose` field any more.  So we will still need specialized behavior.
- There may be some proof types to which an `owner` does not even make sense.  See also @ChristopherA's ideas for "smart signatures" where a proof is the evaluation of a predicate
- In both VC and activitypub you *still have to* check against `issuer` and `actor` anyway.  Missing that will still lead to a security vulnerability.  So trying to ensure that the verification case of identity-centric statements aren't missed is important, but just doing it through owner appears as if it will miss it anyway.  We should probably have a plugin section for what to do right for statement-oriented checks.
- There's still good reason to sign things with one-off keys, and it seems like this is hard to do in the `owner` case, and may give an impression that such cases aren't valuable by requiring to create essentially anonymous owners just to satifsfy LDS

**Comment by dmitrizagidulin** [comment]
The `owner` field has been removed from the spec, this issue can be closed.
